"""Build or update a durable project memory summary from current repo state.

Scans handbooks, scripts, runs, outputs, and docs to produce a structured
PROJECT_MEMORY.md that lets a fresh session or fresh agent session
understand what has been built, what the current state is, and where to
pick up.

This is a summary/index — it does not invent facts. Everything it reports
is derived from files on disk.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, UTC
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MEMORY_DIR = PROJECT_ROOT / "docs" / "memory"


def scan_dir(directory: Path, pattern: str = "*") -> list[str]:
    """Return sorted relative paths matching pattern under directory."""
    if not directory.exists():
        return []
    return sorted(
        str(p.relative_to(PROJECT_ROOT))
        for p in directory.rglob(pattern)
        if p.is_file()
    )


def scan_handoffs(runs_dir: Path) -> list[dict]:
    """Load handoff JSONs from runs/ and return summaries."""
    handoffs = []
    if not runs_dir.exists():
        return handoffs
    for p in sorted(runs_dir.glob("*.json")):
        if p.name.startswith("."):
            continue
        try:
            data = json.loads(p.read_text())
            handoffs.append({
                "file": str(p.relative_to(PROJECT_ROOT)),
                "handoff_type": data.get("handoff_type", "unknown"),
                "run_id": data.get("run_id", "unknown"),
                "summary": data.get("summary", ""),
                "ready_for": data.get("ready_for", ""),
            })
        except Exception:
            handoffs.append({
                "file": str(p.relative_to(PROJECT_ROOT)),
                "handoff_type": "parse-error",
                "run_id": "",
                "summary": "",
                "ready_for": "",
            })
    return handoffs


def count_lines(path: Path) -> int:
    """Count lines in a text file, return 0 on error."""
    try:
        return len(path.read_text().splitlines())
    except Exception:
        return 0


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Build or update the durable project memory summary."
    )
    parser.add_argument(
        "-o", "--output",
        default=str(MEMORY_DIR / "PROJECT_MEMORY.md"),
        help="Output path for the project memory file (default: memory/PROJECT_MEMORY.md)",
    )
    args = parser.parse_args()

    MEMORY_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(UTC).isoformat()

    # --- Scan repo state ---
    handbooks_roles = scan_dir(PROJECT_ROOT / "docs" / "handbooks" / "roles", "*.md")
    handbooks_workflows = scan_dir(PROJECT_ROOT / "docs" / "handbooks" / "workflows", "*.md")
    handbooks_sources = scan_dir(PROJECT_ROOT / "docs" / "handbooks" / "sources", "*.md")
    scripts_py = scan_dir(PROJECT_ROOT / "scripts", "*.py")
    scripts_sh = scan_dir(PROJECT_ROOT / "scripts", "*.sh")
    handoffs = scan_handoffs(PROJECT_ROOT / "runs")
    outputs = scan_dir(PROJECT_ROOT / "outputs")
    data_raw = scan_dir(PROJECT_ROOT / "data" / "raw")
    data_processed = scan_dir(PROJECT_ROOT / "data" / "processed")
    templates = scan_dir(PROJECT_ROOT / "templates")
    lessons_file = MEMORY_DIR / "lessons-learned.jsonl"
    retros = scan_dir(MEMORY_DIR / "retrospectives")

    # Count total Python script lines
    total_py_lines = sum(
        count_lines(PROJECT_ROOT / s)
        for s in scripts_py
    )

    # --- Determine milestone status from ROADMAP.md ---
    roadmap = PROJECT_ROOT / "ROADMAP.md"
    milestones_complete = []
    milestones_planned = []
    if roadmap.exists():
        for line in roadmap.read_text().splitlines():
            if line.startswith("## Milestone"):
                if "✓" in line:
                    milestones_complete.append(line.replace("## ", "").strip())
                else:
                    milestones_planned.append(line.replace("## ", "").strip())

    # Count lessons
    lesson_count = 0
    if lessons_file.exists():
        lesson_count = sum(
            1 for line in lessons_file.read_text().splitlines()
            if line.strip()
        )

    # --- Build markdown ---
    lines = [
        "# Project Memory — GIS Analyst Agent Team",
        "",
        f"*Auto-generated by `scripts/update_project_memory.py` at {now}*",
        "",
        "This file is a durable summary of what has been built in this project.",
        "It is intended to help a fresh session, fresh agent session, or new",
        "contributor understand the current state without reading every file.",
        "",
        "**This is a summary/index, not a source of truth.** If this file conflicts",
        "with the actual repo state, trust the repo.",
        "",
        "---",
        "",
        "## Milestone Status",
        "",
    ]
    for m in milestones_complete:
        lines.append(f"- [x] {m}")
    for m in milestones_planned:
        lines.append(f"- [ ] {m}")

    lines += [
        "",
        "---",
        "",
        "## Team Roles",
        "",
    ]
    for h in handbooks_roles:
        name = Path(h).stem.replace("-", " ").title()
        lines.append(f"- **{name}** — `{h}`")

    lines += [
        "",
        "## Workflow Handbooks",
        "",
    ]
    for h in handbooks_workflows:
        name = Path(h).stem.replace("-", " ").title()
        lines.append(f"- {name} — `{h}`")

    lines += [
        "",
        "## Source Handbooks",
        "",
    ]
    for h in handbooks_sources:
        name = Path(h).stem.replace("-", " ").title()
        lines.append(f"- {name} — `{h}`")

    lines += [
        "",
        "---",
        "",
        f"## Scripts ({len(scripts_py)} Python, {len(scripts_sh)} shell, ~{total_py_lines} lines)",
        "",
    ]
    for s in scripts_py:
        lines.append(f"- `{s}`")
    for s in scripts_sh:
        lines.append(f"- `{s}`")

    lines += [
        "",
        "---",
        "",
        "## Run Handoff Artifacts",
        "",
    ]
    if handoffs:
        for h in handoffs:
            status = f" — {h['ready_for']}" if h["ready_for"] else ""
            lines.append(f"- `{h['file']}` ({h['handoff_type']}{status})")
    else:
        lines.append("- *(none yet)*")

    lines += [
        "",
        "## Key Outputs",
        "",
    ]
    if outputs:
        for o in outputs:
            lines.append(f"- `{o}`")
    else:
        lines.append("- *(none yet)*")

    lines += [
        "",
        "## Data Assets",
        "",
        f"- **Raw**: {len(data_raw)} files in `data/raw/`",
        f"- **Processed**: {len(data_processed)} files in `data/processed/`",
        "",
        "---",
        "",
        "## Memory & Learning",
        "",
        f"- **Lessons logged**: {lesson_count}",
        f"- **Retrospectives**: {len(retros)}",
        "",
    ]
    if retros:
        for r in retros:
            lines.append(f"  - `{r}`")
        lines.append("")

    lines += [
        "---",
        "",
        "## Templates",
        "",
    ]
    for t in templates:
        lines.append(f"- `{t}`")

    lines += [
        "",
        "---",
        "",
        "## How to Use This File",
        "",
        "1. Read this file to understand what the project contains right now.",
        "2. Check ROADMAP.md for milestone details and future plans.",
        "3. Check `memory/lessons-learned.jsonl` for accumulated team knowledge.",
        "4. Check `memory/retrospectives/` for run-level retrospectives.",
        "5. Re-run `python scripts/update_project_memory.py` to refresh this summary.",
        "",
    ]

    out = Path(args.output).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))

    print("=== Project Memory Updated ===")
    print(f"  milestones complete: {len(milestones_complete)}")
    print(f"  milestones planned:  {len(milestones_planned)}")
    print(f"  role handbooks:      {len(handbooks_roles)}")
    print(f"  workflow handbooks:  {len(handbooks_workflows)}")
    print(f"  scripts:             {len(scripts_py)} py, {len(scripts_sh)} sh")
    print(f"  handoff artifacts:   {len(handoffs)}")
    print(f"  outputs:             {len(outputs)}")
    print(f"  lessons:             {lesson_count}")
    print(f"  retrospectives:      {len(retros)}")
    print(f"wrote project memory -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
