"""Generate QGIS packages for all active analyses in the registry.

Reads analyses/registry.json, finds GeoPackage files for each active
analysis, and generates a self-contained QGIS review package in each
analysis's outputs/qgis/ directory.

Each package contains:
  - data/*.gpkg  — copies of all processed + map gpkg files
  - <slug>.qgs   — QGIS project file with relative paths
  - README.md    — usage instructions
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

# Ensure sibling scripts are importable
SCRIPTS_CORE = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_CORE))

PROJECT_ROOT = SCRIPTS_CORE.parents[1]
ANALYSES_DIR = PROJECT_ROOT / "analyses"
REGISTRY_PATH = ANALYSES_DIR / "registry.json"

from write_qgis_project import build_qgs_from_gpkg


def find_gpkg_files(analysis_dir: Path) -> list[Path]:
    """Find all relevant GeoPackage files for an analysis.

    Searches (in order):
      1. data/processed/*.gpkg
      2. outputs/maps/*.gpkg
      3. data/*.gpkg (direct, for older layouts like atl-heat-equity)
      4. outputs/*.gpkg (direct, for outputs like scored_sites.gpkg)
    """
    found = []
    seen_names = set()

    search_dirs = [
        analysis_dir / "data" / "processed",
        analysis_dir / "outputs" / "maps",
        analysis_dir / "data",
        analysis_dir / "outputs",
    ]

    for d in search_dirs:
        if not d.is_dir():
            continue
        for gpkg in sorted(d.glob("*.gpkg")):
            if gpkg.name not in seen_names:
                seen_names.add(gpkg.name)
                found.append(gpkg)

    return found


def package_analysis(
    analysis_dir: Path,
    title: str,
) -> dict:
    """Generate QGIS package for a single analysis."""
    gpkg_files = find_gpkg_files(analysis_dir)

    if not gpkg_files:
        return {
            "status": "skip",
            "reason": "no gpkg files found",
            "files": 0,
        }

    qgis_dir = analysis_dir / "outputs" / "qgis"
    data_dir = qgis_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    copied = []
    errors = []

    # Copy gpkg files to data/
    for src in gpkg_files:
        dest = data_dir / src.name
        try:
            shutil.copy2(src, dest)
            copied.append(dest)
        except Exception as e:
            errors.append(f"copy failed {src.name}: {e}")

    if not copied:
        return {"status": "error", "reason": "no files copied", "files": 0, "errors": errors}

    # Generate .qgs
    slug = analysis_dir.name.replace("-", "_")
    qgs_path = qgis_dir / f"{slug}.qgs"
    rel_paths = [Path("data") / f.name for f in copied]

    try:
        build_qgs_from_gpkg(
            gpkg_paths=rel_paths,
            title=title,
            output_path=qgs_path,
        )
    except Exception as e:
        errors.append(f"qgs generation: {e}")

    # Write README.md
    readme = qgis_dir / "README.md"
    gpkg_bullets = "\n".join(f"  - `data/{f.name}`" for f in copied)
    readme.write_text(
        f"# {title} — QGIS Package\n\n"
        f"Self-contained QGIS review package for **{analysis_dir.name}**.\n\n"
        f"## How to open\n\n"
        f"1. Open QGIS (>= 3.22)\n"
        f"2. File → Open Project → select `{slug}.qgs`\n"
        f"3. All layers load automatically with relative paths\n\n"
        f"## Files\n\n"
        f"- `{slug}.qgs` — QGIS project file\n"
        f"{gpkg_bullets}\n"
        f"- `README.md` — this file\n\n"
        f"## CRS\n\n"
        f"Project CRS: EPSG:4269 (NAD83)\n\n"
        f"---\n"
        f"*Generated by gis-agent*\n"
    )

    total_size = sum(f.stat().st_size for f in copied)
    return {
        "status": "ok" if not errors else "partial",
        "qgs": f"{slug}.qgs",
        "files": len(copied),
        "size_mb": round(total_size / (1024 * 1024), 1),
        "errors": errors,
    }


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="Generate QGIS packages for all active analyses")
    parser.add_argument("--base-dir", default=str(PROJECT_ROOT), help="Project root directory")
    args = parser.parse_args()

    registry_path = Path(args.base_dir) / "analyses" / "registry.json"

    # Load registry
    if not registry_path.exists():
        print(f"ERROR: registry not found: {registry_path}", file=sys.stderr)
        return 1

    registry = json.loads(registry_path.read_text())
    analyses = registry.get("analyses", [])

    # Filter to active analyses
    active = [a for a in analyses if a.get("status") == "active"]
    print(f"Found {len(active)} active analyses in registry\n")

    results = []
    for entry in active:
        aid = entry["id"]
        title = entry["name"]
        analysis_dir = ANALYSES_DIR / aid

        if not analysis_dir.is_dir():
            results.append({"id": aid, "status": "skip", "reason": "dir missing", "files": 0})
            continue

        result = package_analysis(analysis_dir, title)
        result["id"] = aid
        results.append(result)

        status_icon = {"ok": "✓", "partial": "~", "skip": "-", "error": "✗"}.get(result["status"], "?")
        print(f"  {status_icon} {aid:<30s} {result['status']:<8s} {result.get('files', 0)} files"
              + (f"  ({result.get('size_mb', 0)} MB)" if result.get('size_mb') else "")
              + (f"  [{result.get('reason', '')}]" if result.get('reason') else ""))

        if result.get("errors"):
            for e in result["errors"]:
                print(f"      ERROR: {e}")

    # Summary table
    ok_count = sum(1 for r in results if r["status"] == "ok")
    partial_count = sum(1 for r in results if r["status"] == "partial")
    skip_count = sum(1 for r in results if r["status"] == "skip")
    error_count = sum(1 for r in results if r["status"] == "error")
    total_files = sum(r.get("files", 0) for r in results)
    total_mb = sum(r.get("size_mb", 0) for r in results)

    print(f"\n{'='*60}")
    print(f"QGIS Package Generation Summary")
    print(f"{'='*60}")
    print(f"  OK:      {ok_count}")
    if partial_count:
        print(f"  Partial: {partial_count}")
    if skip_count:
        print(f"  Skipped: {skip_count}")
    if error_count:
        print(f"  Errors:  {error_count}")
    print(f"  Total:   {len(results)} analyses, {total_files} gpkg files, {total_mb:.1f} MB")
    print(f"{'='*60}")

    return 1 if error_count > 0 else 0


if __name__ == "__main__":
    raise SystemExit(main())
